/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.vcai.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;
import java.util.Objects;

/**
 *
 * @author avbravo
 */
@Entity
public class Diagnostico {
    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long iddiagnistico;
    @Column
    private String diagnostico;
    @Column
    private Boolean activo;

    public Diagnostico() {
    }

    public Diagnostico(Long iddiagnistico, String diagnostico, Boolean activo) {
        this.iddiagnistico = iddiagnistico;
        this.diagnostico = diagnostico;
        this.activo = activo;
    }

    public Long getIddiagnistico() {
        return iddiagnistico;
    }

    public void setIddiagnistico(Long iddiagnistico) {
        this.iddiagnistico = iddiagnistico;
    }

    public String getDiagnostico() {
        return diagnostico;
    }

    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }

    public Boolean getActivo() {
        return activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Diagnostico other = (Diagnostico) obj;
        if (!Objects.equals(this.diagnostico, other.diagnostico)) {
            return false;
        }
        if (!Objects.equals(this.iddiagnistico, other.iddiagnistico)) {
            return false;
        }
        return Objects.equals(this.activo, other.activo);
    }

    @Override
    public String toString() {
        return "Diagnostico{" + "iddiagnistico=" + iddiagnistico + ", diagnostico=" + diagnostico + ", activo=" + activo + '}';
    }
    
    
            
          
}
